// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo1DeprmIEF0eZrmh7ovakRy7e4x2S19A',
    appId: '1:980769154098:web:02c01c5676cdbd6f70482b',
    messagingSenderId: '980769154098',
    projectId: 'chatpdm-bd250',
    authDomain: 'chatpdm-bd250.firebaseapp.com',
    databaseURL: 'https://chatpdm-bd250-default-rtdb.firebaseio.com',
    storageBucket: 'chatpdm-bd250.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgQm3V0OLlqky9-bStQB1ElEN7KjcLgyU',
    appId: '1:980769154098:android:5e23f0ba6477070370482b',
    messagingSenderId: '980769154098',
    projectId: 'chatpdm-bd250',
    databaseURL: 'https://chatpdm-bd250-default-rtdb.firebaseio.com',
    storageBucket: 'chatpdm-bd250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoEn3G6ZOmu8guJIDO00ZCGIAYmx2oQPM',
    appId: '1:980769154098:ios:d71dbaaaaa8e834d70482b',
    messagingSenderId: '980769154098',
    projectId: 'chatpdm-bd250',
    databaseURL: 'https://chatpdm-bd250-default-rtdb.firebaseio.com',
    storageBucket: 'chatpdm-bd250.appspot.com',
    iosBundleId: 'com.example.projetoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoEn3G6ZOmu8guJIDO00ZCGIAYmx2oQPM',
    appId: '1:980769154098:ios:074da11dd67fd52d70482b',
    messagingSenderId: '980769154098',
    projectId: 'chatpdm-bd250',
    databaseURL: 'https://chatpdm-bd250-default-rtdb.firebaseio.com',
    storageBucket: 'chatpdm-bd250.appspot.com',
    iosBundleId: 'com.example.projetoChat.RunnerTests',
  );
}
